archives/api/urls.py
from django.conf.urls import url

from archives.api.views import ArchivePostAPIView, ArchivePostDetailsAPIView

urlpatterns = [
    url(r'^$', ArchivePostAPIView.as_view(), name='archive-post'),
    url(r'^(?P<pk>[\w.@+-]+)/$',
        ArchivePostDetailsAPIView.as_view(), name="archive-post-details"),
]

archives/urls.py
from django.conf.urls import url

from archives.views import ArchivesPostView

urlpatterns = [
    url(r'^$', ArchivesPostView.as_view(), name="archive-post"),
]

artplusx/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^api/', include('archives.api.urls', namespace='archives-api')),
    url(r'^archive/', include('archives.urls', namespace='archives')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

archives/models.py
import uuid

from django.db import models
from sorl.thumbnail import ImageField

def scramble_uploaded_image(instance, filename):
    extension = filename.split(".")[-1]
    return "archive/{}.{}".format(uuid.uuid4(), extension)


class ArchivePost(models.Model):
    title = models.CharField(max_length=255, blank=True)
    image = ImageField(upload_to=scramble_uploaded_image)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

archives/forms.py
from django import forms

from archives.models import ArchivePost


class ArchivePostForm(forms.ModelForm):
    class Meta:
        model = ArchivePost
        fields = ('title',
                  'image',
                  'description',)

archives/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import generics, permissions
# from rest_framework.authtoken.models import Token
# from rest_framework.response import Response
# from rest_framework.status import HTTP_200_OK, HTTP_400_BAD_REQUEST
# from rest_framework.views import APIView

from archives.models import ArchivePost
from archives.api.serializers import ArchivePostSerializer
# from utils.permissions import IsOwnerOrReadOnly
# from utils.paginations import UserResultPagination, StandardResultPagination

User = get_user_model()


class ArchivePostAPIView(generics.ListCreateAPIView):
    queryset = ArchivePost.objects.get_queryset()
    serializer_class = ArchivePostSerializer


class ArchivePostDetailsAPIView(generics.RetrieveUpdateDestroyAPIView):
    queryset = ArchivePost.objects.all()
    serializer_class = ArchivePostSerializer

archives/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.views import View
from django.views.generic.detail import DetailView

from archives.forms import ArchivePostForm
from archives.models import ArchivePost


class ArchivesPostView(View):
    def get(self, request):
        form = ArchivePostForm()
        archives_list = ArchivePost.objects.all()
        return render(self.request,
                      'index.html',
                      {
                        'archives': archives_list,
                        'form': form
                      })

    def post(self, request):
        form = ArchivePostForm(self.request.POST, self.request.FILES)
        if form.is_valid():
            archive = form.save()
            data = {
                'is_valid': True,
                'title': archive.title,
                'url': archive.image.url,
                'description': archive.description
            }
        else:
            data = {'is_valid': False}
        print(data)
        return JsonResponse(data)


class ArchivePostDetailView(DetailView):
    model = ArchivePost

    def get_context_data(self, **kwargs):
        pass

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Art+x{% endblock %}</title>
    <link href="{% static 'semantic.min.css' %}" rel="stylesheet">
    <link href="{% static 'styles.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    {% include 'header.html' %}
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>

    <script src="{% static 'jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'semantic.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>

</html>

templates/header.html
<div class="navbar">
  <h1 class="logo">Art+X</h1>
</div>

templates/home.html
home

templates/index.html
{% extends 'base.html' %}

{% load static %}
{% load thumbnail %}

{% block javascript %}
  <!-- <script src="{% static 'jquery.ui.widget.js' %}"></script>
  <script src="{% static 'jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'jquery.fileupload.js' %}"></script> -->
  <script src="{% static 'basic-upload.js' %}"></script>
  <script src="{% static 'masonry.pkgd.min.js' %}"></script>
{% endblock %}

{% block content %}
  <!-- <div style="margin-bottom: 20px;">
    <button type="button" class="btn btn-primary js-upload-photos">
      <span class="glyphicon glyphicon-cloud-upload"></span> 사진 업로드
    </button>

    <input id="fileupload" type="file" name="file" multiple
           style="display: none;"
           data-url="{% url 'archives:archive-post' %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
  </div> -->

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>

  <hr>

  <div class="ui grid">
    <div class="two wide column"></div>
    <div class="twelve wide column">
      <div class="masonry-grid">
        <div class="ui link cards">
          {% for archive in archives %}
            <div class="grid-item">
              <div class="ui card">
                <a class="image" href="{{ archive.image.url }}">
                  {% thumbnail archive.image "200" as im %}
                    <img src="{{ im.url }}">
                  {% endthumbnail %}
                </a>
                <div class="content">
                  <a class="header" href="#">{{ archive.title }}</a>
                  <div class="meta">
                    <a>{{ archive.description }}</a>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
    <div class="two wide column"></div>
  </div>

  <!-- <table id="gallery" class="table table-bordered">
    <thead>
      <tr>
        <th>이미지</th>
      </tr>
    </thead>
    <tbody>
      {% for archive in archives %}
        <tr>
          <td>
            <a href="{{ archive.image.url }}">
              {% thumbnail archive.image "100x100" crop="center" as im %}
                <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
              {% endthumbnail %}
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table> -->

  <!-- <p><a href="{% url 'home' %}">Return to home</a></p> -->
{% endblock %}